server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive # Bắt buộc chạy Reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service-route
          uri: lb://PRODUCT-SERVICE  
          predicates:
            - Path=/api/v1/products/** 

        - id: product-service-route
          uri: lb://PRODUCT-SERVICE  
          predicates:
            - Path=/api/v1/admin/products/** 

        - id: product-service-route
          uri: lb://PRODUCT-SERVICE  
          predicates:
            - Path=/api/v1/categories/**
            
        - id: product-service-route
          uri: lb://PRODUCT-SERVICE  
          predicates:
            - Path=/api/v1/brands/** 

        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
            
        - id: auth-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# BẬT LOG ĐỂ SOI LỖI (Quan trọng)
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG