server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive # Bắt buộc chạy Reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Tự động tạo route theo tên service
          lower-case-service-id: true # Cho phép dùng tên thường (product-service)
      routes:
        # Route thủ công (Ưu tiên dùng cái này test trước)
        - id: product-service-route
          uri: lb://PRODUCT-SERVICE  # Tên in hoa y hệt trên bảng Eureka
          predicates:
            - Path=/api/v1/products/** # Link bắt đầu thế này thì chuyển
          
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# BẬT LOG ĐỂ SOI LỖI (Quan trọng)
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG