server:
  port: 8081

spring:
  application:
    name: user-service
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: public
    validate-on-migrate: true

  # OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
            # Chú ý: Redirect URI này phải khớp 100% với cấu hình trên Meta Dashboard
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          facebook:
            # Thay v18.0 bằng phiên bản mới nhất (ví dụ v24.0)
            authorization-uri: https://www.facebook.com/v24.0/dialog/oauth
            token-uri: https://graph.facebook.com/v24.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v24.0/me?fields=id,name,email,picture
            user-name-attribute: id

# Application OAuth2 Configuration
app:
  oauth2:
    # URL frontend sẽ nhận sau khi login OAuth2 thành công (BFF Pattern)
    redirect-uri: ${OAUTH2_REDIRECT_URI:http://localhost:5173/oauth2/callback}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

# Refresh Token Configuration
refresh-token:
  expiration: ${REFRESH_TOKEN_EXPIRATION:604800000}

# Cookie Configuration
cookie:
  http-only: ${COOKIE_HTTP_ONLY:true}
  secure: ${COOKIE_SECURE:true}
  same-site: ${COOKIE_SAME_SITE:Strict}
  path: ${COOKIE_PATH:/}
  access-token-max-age: ${COOKIE_ACCESS_TOKEN_MAX_AGE:86400}
  refresh-token-max-age: ${COOKIE_REFRESH_TOKEN_MAX_AGE:604800}


logging:
  level:
    root: INFO
    com.ecom.user_service: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: DEBUG

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/  # Địa chỉ của Discovery Server
#     fetch-registry: true # Lấy danh sách các service khác về
#     register-with-eureka: true # Đăng ký chính mình lên server
#   instance:
#     prefer-ip-address: true
